from glob import glob

from setuptools import find_packages, setup

package_name = "warehouse_sim"

setup(
    name=package_name,
    version="0.0.0",
    packages=find_packages(exclude=["test", "test.*"]),
    data_files=[
        ("share/ament_index/resource_index/packages", [f"resource/{package_name}"]),
        (f"share/{package_name}", ["package.xml"]),
        (f"share/{package_name}/launch", glob("launch/*.py")),
        # Static occupancy map consumed by Nav2 map_server via nav2_bringup map:=
        # <share>/maps/map.yaml (doc09:255-257). Generated by map_generator.py.
        (f"share/{package_name}/maps", glob("maps/*")),
        # Recording RViz config for #156 (selected by sim.launch.py rviz_config:=record).
        (f"share/{package_name}/rviz", glob("rviz/*")),
    ],
    install_requires=["setuptools"],
    zip_safe=True,
    maintainer="kawaguchiryuya",
    maintainer_email="ryu3124ruyu@gmail.com",
    description="Gazebo world, ros_gz_bridge and sim launch.",
    license="Apache-2.0",
    tests_require=["pytest"],
    entry_points={
        "console_scripts": [
            # Synthetic battery publisher (#44/#156): gz has no battery sensor, but the
            # State Cache gates a bot's snapshot on battery (doc12:293), so the bot needs
            # /bot{n}/battery to reach the LLM's situation JSON. See warehouse_sim.battery.
            "sim_battery_publisher = warehouse_sim.battery_publisher:main",
        ],
    },
)
