"""Generate the Gazebo (gz-sim8) world SDF from layout constants (single source).

``build_world_sdf`` is a pure function (no ROS / gz) so it is unit-testable as text. It
reuses the world-plugin + lighting block proven in the environment spike
(``spike/worlds/min_lidar.sdf``): physics + user-commands + scene-broadcaster + sensors
(ogre2). World extents come only from ``layout.py`` — this module contains no literal
1.8 / 0.9 (the single-source guard test checks that).
"""

from warehouse_sim.layout import WORLD_X, WORLD_Y, Box, world_boxes

WORLD_NAME = "warehouse"

_HEADER = """\
<?xml version="1.0" ?>
<!-- Generated by warehouse_sim.world_generator from layout.py — do not edit by hand. -->
<sdf version="1.8">
  <world name="{name}">
    <physics name="1ms" type="ignored">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <light type="directional" name="sun">
      <cast_shadows>false</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.8 0.8 0.8 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>-0.5 0.1 -0.9</direction>
    </light>
    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>{gx} {gy}</size></plane></geometry>
        </collision>
        <visual name="visual">
          <geometry><plane><normal>0 0 1</normal><size>{gx} {gy}</size></plane></geometry>
          <material><ambient>0.8 0.8 0.8 1</ambient><diffuse>0.8 0.8 0.8 1</diffuse></material>
        </visual>
      </link>
    </model>"""

_FOOTER = """
  </world>
</sdf>
"""


def _box_model(b: Box) -> str:
    return f"""\
    <model name="{b.name}">
      <static>true</static>
      <pose>{b.x} {b.y} {b.z} 0 0 0</pose>
      <link name="link">
        <collision name="collision">
          <geometry><box><size>{b.sx} {b.sy} {b.sz}</size></box></geometry>
        </collision>
        <visual name="visual">
          <geometry><box><size>{b.sx} {b.sy} {b.sz}</size></box></geometry>
          <material><ambient>0.5 0.5 0.55 1</ambient><diffuse>0.5 0.5 0.55 1</diffuse></material>
        </visual>
      </link>
    </model>"""


def build_world_sdf(boxes: list[Box] | None = None) -> str:
    """Return the full world SDF string for the diorama (walls, shelves, aisle pinch, markers)."""
    boxes = world_boxes() if boxes is None else boxes
    ground_x = WORLD_X + 0.4
    ground_y = WORLD_Y + 0.4
    header = _HEADER.format(name=WORLD_NAME, gx=ground_x, gy=ground_y)
    models = "\n".join(_box_model(b) for b in boxes)
    return f"{header}\n{models}{_FOOTER}"
